### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ghost**
Spelling.

* Description of what the PR does, such as fixes # {issue number}

* Description of how to validate or test this PR

* Whether you have signed a CLA (Contributor Licensing Agreement)

### CODE REVIEW

**Comment by KathyReid** [comment]
Thank you  so much for your PR, @L3vi47h4N, we really appreciate you picking up the spelling error. 

To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code contribution.
This agreement makes it crystal clear that along with your code you are
offering a license to use it within the confines of this project. You retain
ownership of the code, this is just a license.

Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!

**Comment by ghost** [comment]
I sent the CLA request but haven't get gotten an email. Feel free to fix this issue yourself and close this PR if it is more convenient. I'm not worried about attribution for something so minor. 

Thanks!

**Comment by ghost** [comment]
Yeah received the "CLA" nothing unreasonable in it, but I'm not giving you my address. I'll go ahead and close this.

**Comment by penrods** [comment]
@L3vi47h4N no problem, I know it seems a little silly for something as trivial as this change.  I've considered whether we can create an exception for "simple" changes, but that is where it starts to get slippery.  So I'm holding with the "every commit requires a CLA" stand for now.  I hope you understand.

I'll go ahead and fix that typo myself.  If you see other simple things like this, you can just point them out in an Issue and we can do them for you.  If you do choose to use the CLA, I promise you that the address is only for the CLA signature -- we respect privacy and that is why we make publishing your real name optional.  We want to give credit to those who help build this, but don't want to force them into the limelight if they'd rather avoid it!

Thanks again!

**Pull request closed without merging**
