### PR TITLE
Fix for Matrix Certificate not trusted

### PR DESCRIPTION
**Pull request by derme302**
* Description of what the PR does, such as fixes # {issue number}
This is a fix for #143, by running `update-ca-certificates` it forces the system to update the certificate store.

* Description of how to validate or test this PR
Run the script & enjoy less errors.

* Whether you have signed a CLA (Contributor Licensing Agreement)
No - I couldn't find it. I agree for this to be released though.

### CODE REVIEW

**Comment by krisgesling** [comment]
Hi derme, thanks for digging into this.

I wonder if we should update the cert store on some regular basis anyway?

To initiate the CLA signing process head to: http://mycroft.ai/cla

This agreement clarifies that you are granting a license to the Mycroft Project to freely use your work.  Additionally, it establishes that you retain the ownership of your contributed code and intellectual property.  As the owner, you are free to use your code in other work, obtain patents, or do anything else you choose with it. You also get added to our [list of excellent humans](https://github.com/MycroftAI/contributors).

**Comment by krisgesling** [comment]
CLA received, we're just in the middle of a major release so I'm going to come back to this when I have a clear head to think of the best place to insert the update.

Other opinions most welcome :)

**Comment by derme302** [comment]
Hey Kris, awesome! The certificate store only needs to be updated when you add or remove certificates - no need to update it on a regular basis.

**Comment by krisgesling** [comment]
Hey, that makes sense. Was not thinking clearly above. 

Merging, thanks again :)

**Pull request merged**
