### PR TITLE
Remove WEP description from auto_run.sh first-time setup menu

### PR DESCRIPTION
**Pull request by gregrs-uk**
* Description of what the PR does, such as fixes # {issue number}

Removes reference to WEP in first-time setup menu. Basic wifi setup also works for WPA so mentioning WEP is confusing for the user.

* Description of how to validate or test this PR

`touch ~/first_run` then `./auto_run.sh`

* Whether you have signed a CLA (Contributor Licensing Agreement)

No

### CODE REVIEW

**Comment by penrods** [comment]
Thanks for the catch, I totally agree.

**Comment by penrods** [comment]
@gregrs-uk we try to be keep everything very clean, so even with minor PRs we would like to have a CLA and to list you on the [Contributors List](https://github.com/MycroftAI/contributors).  Can you please visit the page https://mycroft.ai/cla to get the process rolling?

**Comment by gregrs-uk** [comment]
Signed. Thanks.

**Comment by penrods** [comment]
Thank you!

**Pull request merged**
